# Generated by Django 5.1 on 2024-11-20 08:42

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', storage=storages.backends.s3.S3Storage(), upload_to='profile_pics'),
        ),
    ]
